apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-manager
  namespace: ozhera-namespace
  labels:
    app: log-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-manager
  template:
    metadata:
      labels:
        app: log-manager
    spec:
      containers:
      - name: log-manager-container
        image: herahub/opensource-pub:log-manager-v1-release-0.2
        env:
          - name: MIONE_PROJECT_ENV_NAME
            value: dev
          - name: MIONE_PROJECT_ENV_ID
            value: '12'
          - name: MIONE_PROJECT_NAME
            value: 12-log-manager
        volumeMounts:
          - name: log-path
            mountPath: /home/work/log
        resources:
          limits:
            cpu: '500m'
            memory: 2Gi

      - name: log-agent
        image: herahub/opensource-pub:log-agent-v1-release-0.2
        volumeMounts:
          - mountPath: "/home/work/log"
            name: log-path
        resources:
          limits:
            cpu: '300m'
            memory: 1Gi
      volumes:
        - name: log-path
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: log-manager
  namespace: ozhera-namespace
  labels:
    app: log-manager
spec:
  ports:
    - port: 7788
      targetPort: 7788
      protocol: TCP
  selector:
    app: log-manager
  clusterIP: None
