apiVersion: apps/v1
kind: Deployment
metadata:
  name: oz-spider
  namespace: infra
  labels:
    app: oz-spider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oz-spider
  template:
    metadata:
      labels:
        app: oz-spider
    spec:
      containers:
        - name: oz-spider-container
          image: herahub/opensource-pub:oz-spider-v1.3
          volumeMounts:
            - name: log-path
              mountPath: /home/work/log/oz-spider
          resources:
            limits:
              cpu: '200m'
              memory: 1Gi
      volumes:
        - name: log-path
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: oz-spider
  namespace: infra
  labels:
    app: oz-spider
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: oz-spider
  clusterIP: None
