apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics-victoria-metrics-cluster-vminsert
  namespace: ozhera-namespace
  labels:
    app: ozhera-vminsert-svc
    app.kubernetes.io/instance: victoria-metrics
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8480
      targetPort: http
  selector:
    app: ozhera-vminsert
    app.kubernetes.io/instance: victoria-metrics
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics-victoria-metrics-cluster-vminsert
  namespace: ozhera-namespace
  labels:
    app: ozhera-vminsert
    app.kubernetes.io/instance: victoria-metrics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ozhera-vminsert
      app.kubernetes.io/instance: victoria-metrics
  template:
    metadata:
      labels:
        app: ozhera-vminsert
        app.kubernetes.io/instance: victoria-metrics
    spec:
      containers:
        - name: victoria-metrics-cluster-vminsert
          image: victoriametrics/vminsert:v1.96.0-cluster
          args:
            - >-
              --storageNode=victoria-metrics-victoria-metrics-cluster-vmstorage-0.victoria-metrics-victoria-metrics-cluster-vmstorage.ozhera-namespace.svc.cluster.local:8400
            - >-
              --storageNode=victoria-metrics-victoria-metrics-cluster-vmstorage-1.victoria-metrics-victoria-metrics-cluster-vmstorage.ozhera-namespace.svc.cluster.local:8400
            - '--envflag.enable=true'
            - '--envflag.prefix=VM_'
            - '--loggerFormat=json'
          ports:
            - name: http
              containerPort: 8480
              protocol: TCP
          resources: {}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: prometheus
      automountServiceAccountToken: true
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

