apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: ${webhook_caBundle}
      service:
        name: hera-webhook-server
        namespace: ozhera-namespace
        path: /hera-env-v1
    failurePolicy: Ignore
    name: pod.hera.mone.run
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
